App:
  Name: yacop-api

Server:
  Port: 1337
  Host: "localhost"

Database:
  User: "postgres"
  Password: "postgres"
  Host: "localhost"
  Port: 5432
  Name: "yacop-api"
  SslMode: "disable"
  MaxOpenConnections: 10