App:
  Name: yacop-api

Server:
  Port: 1337
  Host: "localhost"

Database:
  User: "postgres"
  Password: "thisiselkromerdev"
  Host: "elkromer.dev"
  Port: 5432
  Name: "yacop_dev"
  SslMode: "disable"
  MaxOpenConnections: 10

Keycloak:
  ClientID: "yacop-api"
  JWKS:
    # source url of jwks
    Url: "https://iam.elkromer.dev/auth/realms/yacop/protocol/openid-connect/certs"
    # refresh jwks in n-hour interval
    RefreshInterval: 1